# Copyright 2026 The hermetic-cpp-cmake Authors.
# SPDX-License-Identifier: Apache-2.0
#
# Hermetic C/C++ toolchain for CMake, after hermeticbuild/hermetic-llvm: the
# compiler comes from its prebuilts, and for Linux targets libc (glibc stubs
# or musl), compiler-rt and libc++ are built from source into a "runtime set"
# (or downloaded prebuilt), so no distribution sysroot is needed.
#
#   cmake -S . -B build -DCMAKE_TOOLCHAIN_FILE=<this dir>/toolchain.cmake \
#         -DHERMETIC_LLVM_VERSION=23.1.0 -DHERMETIC_TARGET=linux-aarch64 -DHERMETIC_LIBC=musl
#
# See README.md for every HERMETIC_LLVM_* option.

if(CMAKE_VERSION VERSION_LESS 3.19)
  message(FATAL_ERROR "[hermetic-cpp] CMake 3.19 or newer is required (string(JSON), file(ARCHIVE_EXTRACT))")
endif()

# The toolchain file is loaded more than once per configure; do the work once.
if(_HERMETIC_TOOLCHAIN_LOADED)
  return()
endif()
set(_HERMETIC_TOOLCHAIN_LOADED TRUE)

set(HERMETIC_DIR "${CMAKE_CURRENT_LIST_DIR}")

# ---- Options and defaults --------------------------------------------------
set(_hl_option_names
  HERMETIC_LLVM_VERSION HERMETIC_LLVM_RELEASE HERMETIC_LLVM_HERMETICBUILD_INDEX
  HERMETIC_LLVM_DISTRIBUTION_URL HERMETIC_LLVM_DISTRIBUTION_SHA256 HERMETIC_LLVM_DISTRIBUTION_STRIP_COMPONENTS
  HERMETIC_TARGET HERMETIC_LIBC HERMETIC_CXX_STDLIB HERMETIC_LLVM_RUNTIMES HERMETIC_LLVM_RUNTIME_SET_DIR
  HERMETIC_LLVM_RUNTIME_SETS_FILES HERMETIC_LLVM_RUNTIME_SANITIZERS HERMETIC_KEEP_BUILD_DIRS
  HERMETIC_SYSROOT HERMETIC_SYSROOT_SHA256 HERMETIC_SYSROOT_STRIP_COMPONENTS
  HERMETIC_ACCEPT_MICROSOFT_EULA HERMETIC_MSVC_TOOLSET_VERSION HERMETIC_WINDOWS_SDK_VERSION HERMETIC_WINDOWS_ABI
  HERMETIC_ACCEPT_APPLE_SDK_LICENSE HERMETIC_MACOS_SDK_VERSION
  HERMETIC_PIE HERMETIC_USE_LLD HERMETIC_REPRODUCIBLE HERMETIC_COMPILER
  HERMETIC_EXTRA_COMPILE_FLAGS HERMETIC_EXTRA_CXX_FLAGS HERMETIC_EXTRA_LINK_FLAGS HERMETIC_EXTRA_LINK_LIBS
  HERMETIC_CACHE_DIR HERMETIC_KEEP_ARCHIVES HERMETIC_SHOW_PROGRESS HERMETIC_DOWNLOAD_ARGS
  HERMETIC_MIRROR_URLS HERMETIC_EMULATOR HERMETIC_VERBOSE)
set(_hl_resolved_names
  HERMETIC_RESOLVED HERMETIC_RESOLVED_LLVM_ROOT HERMETIC_RESOLVED_LLVM_VERSION HERMETIC_RESOLVED_LLVM_RELEASE
  HERMETIC_RESOLVED_LLVM_RUNTIME_SET HERMETIC_RESOLVED_SYSROOT HERMETIC_RESOLVED_LIBC HERMETIC_RESOLVED_WINSDK
  HERMETIC_RESOLVED_CXX_STDLIB HERMETIC_RESOLVED_WINDOWS_ABI HERMETIC_RESOLVED_COMPILER HERMETIC_RESOLVED_MSVC_BIN
  HERMETIC_RESOLVED_HOST_OS HERMETIC_RESOLVED_HOST_ARCH)
list(APPEND CMAKE_TRY_COMPILE_PLATFORM_VARIABLES ${_hl_option_names} ${_hl_resolved_names})

if(NOT DEFINED HERMETIC_LLVM_VERSION OR HERMETIC_LLVM_VERSION STREQUAL "")
  set(HERMETIC_LLVM_VERSION "latest")
endif()
if(NOT DEFINED HERMETIC_USE_LLD)
  set(HERMETIC_USE_LLD ON)
endif()
if(NOT DEFINED HERMETIC_COMPILER OR HERMETIC_COMPILER STREQUAL "")
  set(HERMETIC_COMPILER llvm)
endif()
if(NOT DEFINED HERMETIC_REPRODUCIBLE)
  set(HERMETIC_REPRODUCIBLE ON)
endif()

include("${HERMETIC_DIR}/cmake/HermeticCommon.cmake")
include("${HERMETIC_DIR}/cmake/HermeticDistributions.cmake")
include("${HERMETIC_DIR}/cmake/HermeticTargets.cmake")
include("${HERMETIC_DIR}/cmake/HermeticLLVMRuntimes.cmake")
include("${HERMETIC_DIR}/cmake/HermeticWindows.cmake")
include("${HERMETIC_DIR}/cmake/HermeticDarwin.cmake")
include("${HERMETIC_DIR}/cmake/HermeticResolve.cmake")
include("${HERMETIC_DIR}/cmake/HermeticConfigure.cmake")

hermetic_resolve()
hermetic_configure()
