# Copyright 2026 The hermetic-llvm-cmake Authors.
# SPDX-License-Identifier: Apache-2.0
#
# Hermetic LLVM toolchain for CMake, after hermeticbuild/hermetic-llvm: the
# compiler comes from its prebuilts, and for Linux targets libc (glibc stubs
# or musl), compiler-rt and libc++ are built from source into a "runtime set"
# (or downloaded prebuilt), so no distribution sysroot is needed.
#
#   cmake -S . -B build -DCMAKE_TOOLCHAIN_FILE=<this dir>/toolchain.cmake \
#         -DHERMETIC_LLVM_VERSION=23.1.0 -DHERMETIC_LLVM_TARGET=linux-aarch64 -DHERMETIC_LLVM_LIBC=musl
#
# See README.md for every HERMETIC_LLVM_* option.

if(CMAKE_VERSION VERSION_LESS 3.19)
  message(FATAL_ERROR "[hermetic-llvm] CMake 3.19 or newer is required (string(JSON), file(ARCHIVE_EXTRACT))")
endif()

# The toolchain file is loaded more than once per configure; do the work once.
if(_HERMETIC_LLVM_TOOLCHAIN_LOADED)
  return()
endif()
set(_HERMETIC_LLVM_TOOLCHAIN_LOADED TRUE)

set(HERMETIC_LLVM_DIR "${CMAKE_CURRENT_LIST_DIR}")

# ---- Options and defaults --------------------------------------------------
set(_hl_option_names
  HERMETIC_LLVM_VERSION HERMETIC_LLVM_RELEASE HERMETIC_LLVM_HERMETICBUILD_INDEX
  HERMETIC_LLVM_DISTRIBUTION_URL HERMETIC_LLVM_DISTRIBUTION_SHA256 HERMETIC_LLVM_DISTRIBUTION_STRIP_COMPONENTS
  HERMETIC_LLVM_TARGET HERMETIC_LLVM_LIBC HERMETIC_LLVM_CXX_STDLIB HERMETIC_LLVM_RUNTIMES HERMETIC_LLVM_RUNTIME_SET_DIR
  HERMETIC_LLVM_RUNTIME_SETS_FILES HERMETIC_LLVM_RUNTIME_SANITIZERS HERMETIC_LLVM_KEEP_BUILD_DIRS
  HERMETIC_LLVM_SYSROOT HERMETIC_LLVM_SYSROOT_SHA256 HERMETIC_LLVM_SYSROOT_STRIP_COMPONENTS
  HERMETIC_LLVM_ACCEPT_MICROSOFT_EULA HERMETIC_LLVM_MSVC_VERSION HERMETIC_LLVM_WINDOWS_SDK_VERSION
  HERMETIC_LLVM_ACCEPT_APPLE_SDK_LICENSE HERMETIC_LLVM_MACOS_SDK_VERSION
  HERMETIC_LLVM_PIE HERMETIC_LLVM_USE_LLD HERMETIC_LLVM_REPRODUCIBLE
  HERMETIC_LLVM_EXTRA_COMPILE_FLAGS HERMETIC_LLVM_EXTRA_CXX_FLAGS HERMETIC_LLVM_EXTRA_LINK_FLAGS HERMETIC_LLVM_EXTRA_LINK_LIBS
  HERMETIC_LLVM_CACHE_DIR HERMETIC_LLVM_KEEP_ARCHIVES HERMETIC_LLVM_SHOW_PROGRESS HERMETIC_LLVM_DOWNLOAD_ARGS
  HERMETIC_LLVM_MIRROR_URLS HERMETIC_LLVM_EMULATOR HERMETIC_LLVM_VERBOSE)
set(_hl_resolved_names
  HERMETIC_LLVM_RESOLVED HERMETIC_LLVM_RESOLVED_ROOT HERMETIC_LLVM_RESOLVED_VERSION HERMETIC_LLVM_RESOLVED_RELEASE
  HERMETIC_LLVM_RESOLVED_RUNTIME_SET HERMETIC_LLVM_RESOLVED_SYSROOT HERMETIC_LLVM_RESOLVED_LIBC HERMETIC_LLVM_RESOLVED_WINSDK
  HERMETIC_LLVM_RESOLVED_CXX_STDLIB
  HERMETIC_LLVM_RESOLVED_HOST_OS HERMETIC_LLVM_RESOLVED_HOST_ARCH)
list(APPEND CMAKE_TRY_COMPILE_PLATFORM_VARIABLES ${_hl_option_names} ${_hl_resolved_names})

if(NOT DEFINED HERMETIC_LLVM_VERSION OR HERMETIC_LLVM_VERSION STREQUAL "")
  set(HERMETIC_LLVM_VERSION "latest")
endif()
if(NOT DEFINED HERMETIC_LLVM_USE_LLD)
  set(HERMETIC_LLVM_USE_LLD ON)
endif()
if(NOT DEFINED HERMETIC_LLVM_REPRODUCIBLE)
  set(HERMETIC_LLVM_REPRODUCIBLE ON)
endif()

include("${HERMETIC_LLVM_DIR}/cmake/HermeticLLVMCommon.cmake")
include("${HERMETIC_LLVM_DIR}/cmake/HermeticLLVMDistributions.cmake")
include("${HERMETIC_LLVM_DIR}/cmake/HermeticLLVMTargets.cmake")
include("${HERMETIC_LLVM_DIR}/cmake/HermeticLLVMRuntimes.cmake")
include("${HERMETIC_LLVM_DIR}/cmake/HermeticLLVMWindows.cmake")
include("${HERMETIC_LLVM_DIR}/cmake/HermeticLLVMDarwin.cmake")
include("${HERMETIC_LLVM_DIR}/cmake/HermeticLLVMResolve.cmake")
include("${HERMETIC_LLVM_DIR}/cmake/HermeticLLVMConfigure.cmake")

hermetic_llvm_resolve()
hermetic_llvm_configure()
