# Unit test for archive selection, run with `cmake -P tests/select_test.cmake`.
cmake_minimum_required(VERSION 3.19)
get_filename_component(HERMETIC_DIR "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
include("${HERMETIC_DIR}/cmake/HermeticCommon.cmake")
include("${HERMETIC_DIR}/cmake/HermeticDistributions.cmake")
include("${HERMETIC_DIR}/cmake/HermeticTargets.cmake")
include("${HERMETIC_DIR}/cmake/HermeticConfigure.cmake")
include("${HERMETIC_DIR}/cmake/HermeticLLVMRuntimes.cmake")
set(failures 0)

# hermeticbuild compiler prebuilts.
function(expect_hb SPEC OS ARCH EXPECTED_KEY)
  hermetic_llvm_select_hermeticbuild("${SPEC}" "${OS}" "${ARCH}" sel)
  if(NOT sel_KEY STREQUAL EXPECTED_KEY)
    message(SEND_ERROR "select_hermeticbuild(${SPEC}, ${OS}-${ARCH}) = ${sel_KEY}, expected ${EXPECTED_KEY}")
    math(EXPR failures "${failures} + 1")
    set(failures ${failures} PARENT_SCOPE)
  else()
    message(STATUS "ok: select_hermeticbuild(${SPEC}, ${OS}-${ARCH}) = ${sel_KEY} [${sel_RELEASE}] -> ${sel_URLS}")
  endif()
endfunction()
expect_hb(23.1.0 darwin aarch64 "llvm-toolchain-minimal-23.1.0-darwin-arm64.tar.zst")
expect_hb(latest darwin x86_64 "llvm-toolchain-minimal-23.1.2-darwin-amd64.tar.zst")
expect_hb(latest linux x86_64 "llvm-toolchain-minimal-23.1.2-linux-amd64-musl.tar.zst")
expect_hb(latest linux aarch64 "llvm-toolchain-minimal-23.1.2-linux-arm64-musl.tar.zst")
expect_hb(latest windows x86_64 "llvm-toolchain-minimal-23.1.2-windows-amd64.tar.zst")
expect_hb("latest:<23" darwin aarch64 "llvm-toolchain-minimal-22.1.8-darwin-arm64.tar.zst")
expect_hb("first:>=22" darwin aarch64 "llvm-toolchain-minimal-22.1.6-darwin-arm64.tar.zst")
expect_hb(23.1.0-rc1 darwin aarch64 "llvm-toolchain-minimal-23.1.0-rc1-darwin-arm64.tar.zst")
set(HERMETIC_LLVM_RELEASE llvm-21.1.8-10)
expect_hb(latest darwin aarch64 "llvm-toolchain-minimal-21.1.8-darwin-arm64.tar.zst")
unset(HERMETIC_LLVM_RELEASE)

# libc specs and triples.
hermetic_llvm_load_runtime_sources()
hermetic_parse_libc(gnu.2.28 fam ver)
hermetic_libc_triple(x86_64 "${fam}" t1)
hermetic_parse_libc(musl fam2 ver2)
hermetic_libc_triple(armv7 "${fam2}" t2)
if(NOT t1 STREQUAL "x86_64-unknown-linux-gnu" OR NOT t2 STREQUAL "armv7-unknown-linux-musleabihf" OR NOT ver STREQUAL "2.28")
  message(SEND_ERROR "libc triple mapping broken: ${t1} ${t2} ${ver}")
  math(EXPR failures "${failures} + 1")
endif()

# Windows toolset / SDK selection.
include("${HERMETIC_DIR}/cmake/HermeticWindows.cmake")
hermetic_windows_versions(msvc msvc_default sdk sdk_default)
hermetic_llvm_select_version(sdk "10.0.22621" "${sdk_default}" "${sdk}" w1)
hermetic_llvm_select_version(sdk "" "${sdk_default}" "${sdk}" w2)
hermetic_llvm_select_version(msvc "latest" "${msvc_default}" "${msvc}" w3)
hermetic_llvm_select_version(msvc "14.44" "${msvc_default}" "${msvc}" w4)
if(NOT w1 STREQUAL "10.0.22621.3233" OR NOT w2 STREQUAL "10.0.26100.7705" OR NOT w3 STREQUAL "14.51.36014" OR NOT w4 MATCHES "^14\\.44\\.")
  message(SEND_ERROR "windows version selection broken: ${w1} ${w2} ${w3} ${w4}")
  math(EXPR failures "${failures} + 1")
endif()

if(failures)
  message(FATAL_ERROR "${failures} selection test(s) failed")
endif()
message(STATUS "all selection tests passed")
