# Unit test for archive selection, run with `cmake -P tests/select_test.cmake`.
cmake_minimum_required(VERSION 3.19)
get_filename_component(HERMETIC_LLVM_DIR "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
include("${HERMETIC_LLVM_DIR}/cmake/HermeticLLVMCommon.cmake")
include("${HERMETIC_LLVM_DIR}/cmake/HermeticLLVMDistributions.cmake")
include("${HERMETIC_LLVM_DIR}/cmake/HermeticLLVMTargets.cmake")
include("${HERMETIC_LLVM_DIR}/cmake/HermeticLLVMConfigure.cmake")
include("${HERMETIC_LLVM_DIR}/cmake/HermeticLLVMRuntimes.cmake")
set(failures 0)

# hermeticbuild compiler prebuilts.
function(expect_hb SPEC OS ARCH EXPECTED_KEY)
  hermetic_llvm_select_hermeticbuild("${SPEC}" "${OS}" "${ARCH}" sel)
  if(NOT sel_KEY STREQUAL EXPECTED_KEY)
    message(SEND_ERROR "select_hermeticbuild(${SPEC}, ${OS}-${ARCH}) = ${sel_KEY}, expected ${EXPECTED_KEY}")
    math(EXPR failures "${failures} + 1")
    set(failures ${failures} PARENT_SCOPE)
  else()
    message(STATUS "ok: select_hermeticbuild(${SPEC}, ${OS}-${ARCH}) = ${sel_KEY} [${sel_RELEASE}] -> ${sel_URLS}")
  endif()
endfunction()
expect_hb(23.1.0 darwin aarch64 "llvm-toolchain-minimal-23.1.0-darwin-arm64.tar.zst")
expect_hb(latest darwin x86_64 "llvm-toolchain-minimal-23.1.0-darwin-amd64.tar.zst")
expect_hb(latest linux x86_64 "llvm-toolchain-minimal-23.1.0-linux-amd64-musl.tar.zst")
expect_hb(latest linux aarch64 "llvm-toolchain-minimal-23.1.0-linux-arm64-musl.tar.zst")
expect_hb(latest windows x86_64 "llvm-toolchain-minimal-23.1.0-windows-amd64.tar.zst")
expect_hb("latest:<23" darwin aarch64 "llvm-toolchain-minimal-22.1.8-darwin-arm64.tar.zst")
expect_hb("first:>=22" darwin aarch64 "llvm-toolchain-minimal-22.1.6-darwin-arm64.tar.zst")
expect_hb(23.1.0-rc1 darwin aarch64 "llvm-toolchain-minimal-23.1.0-rc1-darwin-arm64.tar.zst")
set(HERMETIC_LLVM_RELEASE llvm-21.1.8-10)
expect_hb(latest darwin aarch64 "llvm-toolchain-minimal-21.1.8-darwin-arm64.tar.zst")
unset(HERMETIC_LLVM_RELEASE)

# libc specs and triples.
hermetic_llvm_load_runtime_sources()
hermetic_llvm_parse_libc(gnu.2.28 fam ver)
hermetic_llvm_libc_triple(x86_64 "${fam}" t1)
hermetic_llvm_parse_libc(musl fam2 ver2)
hermetic_llvm_libc_triple(armv7 "${fam2}" t2)
if(NOT t1 STREQUAL "x86_64-unknown-linux-gnu" OR NOT t2 STREQUAL "armv7-unknown-linux-musleabihf" OR NOT ver STREQUAL "2.28")
  message(SEND_ERROR "libc triple mapping broken: ${t1} ${t2} ${ver}")
  math(EXPR failures "${failures} + 1")
endif()

if(failures)
  message(FATAL_ERROR "${failures} selection test(s) failed")
endif()
message(STATUS "all selection tests passed")
