# Copyright 2026 The hermetic-llvm-cmake Authors.
# SPDX-License-Identifier: Apache-2.0
#
# Toolchain file used while building the runtime sets themselves (libc,
# compiler-rt, libc++). It points CMake at the hermetic compiler for a target
# triple without assuming a sysroot or any runtime library exists yet.
#
# Inputs (cache variables, forwarded to try_compile):
#   HERMETIC_LLVM_BOOTSTRAP_BIN          <llvm>/bin
#   HERMETIC_LLVM_BOOTSTRAP_TRIPLE       e.g. x86_64-unknown-linux-musl
#   HERMETIC_LLVM_BOOTSTRAP_SYSTEM_NAME  Linux or Windows (clang-cl / lld-link, MSVC ABI)
#   HERMETIC_LLVM_BOOTSTRAP_PROCESSOR    x86_64
#   HERMETIC_LLVM_BOOTSTRAP_SYSROOT      optional sysroot (once libc headers exist)
#   HERMETIC_LLVM_BOOTSTRAP_RESOURCE_DIR optional resource dir (once builtins exist)
#   HERMETIC_LLVM_BOOTSTRAP_LINK_TESTS   ON once executables can be linked
#   HERMETIC_LLVM_BOOTSTRAP_EXTRA_FLAGS / _EXTRA_CXX_FLAGS / _CXX_LIBS  extra flags and C++ link libraries
#   HERMETIC_LLVM_BOOTSTRAP_LINK_FLAGS   extra linker flags (Windows: /LIBPATH..., /MACHINE...)
#   HERMETIC_LLVM_BOOTSTRAP_CXX_FIRST_FLAGS  C++ flags placed ahead of the common ones (include order)
#   HERMETIC_LLVM_BOOTSTRAP_LINK_TAIL    Windows: linker options after the project's own (last wins)

list(APPEND CMAKE_TRY_COMPILE_PLATFORM_VARIABLES
  HERMETIC_LLVM_BOOTSTRAP_BIN HERMETIC_LLVM_BOOTSTRAP_TRIPLE HERMETIC_LLVM_BOOTSTRAP_SYSTEM_NAME
  HERMETIC_LLVM_BOOTSTRAP_PROCESSOR HERMETIC_LLVM_BOOTSTRAP_SYSROOT HERMETIC_LLVM_BOOTSTRAP_RESOURCE_DIR
  HERMETIC_LLVM_BOOTSTRAP_LINK_TESTS HERMETIC_LLVM_BOOTSTRAP_EXTRA_FLAGS
  HERMETIC_LLVM_BOOTSTRAP_EXTRA_CXX_FLAGS HERMETIC_LLVM_BOOTSTRAP_CXX_LIBS HERMETIC_LLVM_BOOTSTRAP_PREFIX_MAP
  HERMETIC_LLVM_BOOTSTRAP_LINK_FLAGS HERMETIC_LLVM_BOOTSTRAP_CXX_FIRST_FLAGS HERMETIC_LLVM_BOOTSTRAP_LINK_TAIL)

set(CMAKE_SYSTEM_NAME "${HERMETIC_LLVM_BOOTSTRAP_SYSTEM_NAME}")
set(CMAKE_SYSTEM_PROCESSOR "${HERMETIC_LLVM_BOOTSTRAP_PROCESSOR}")
set(_hb_exe "")
if(CMAKE_HOST_WIN32)
  set(_hb_exe ".exe")
endif()
set(_hb_windows FALSE)
if(HERMETIC_LLVM_BOOTSTRAP_SYSTEM_NAME STREQUAL "Windows")
  set(_hb_windows TRUE)
  set(CMAKE_C_COMPILER "${HERMETIC_LLVM_BOOTSTRAP_BIN}/clang-cl${_hb_exe}")
  set(CMAKE_CXX_COMPILER "${HERMETIC_LLVM_BOOTSTRAP_BIN}/clang-cl${_hb_exe}")
  set(CMAKE_RC_COMPILER "${HERMETIC_LLVM_BOOTSTRAP_BIN}/llvm-rc${_hb_exe}" CACHE FILEPATH "")
  set(CMAKE_MT "${HERMETIC_LLVM_BOOTSTRAP_BIN}/llvm-mt${_hb_exe}" CACHE FILEPATH "")
  # clang-cl assembles .S files too; CMake applies MSVC-style flags to ASM
  # whenever the C compiler is MSVC-like, which plain clang would reject.
  set(CMAKE_ASM_COMPILER "${HERMETIC_LLVM_BOOTSTRAP_BIN}/clang-cl${_hb_exe}")
  set(HERMETIC_LLVM_WINDOWS_LINK_TAIL "${HERMETIC_LLVM_BOOTSTRAP_LINK_TAIL}")
  set(CMAKE_USER_MAKE_RULES_OVERRIDE "${CMAKE_CURRENT_LIST_DIR}/../cmake/HermeticLLVMWindowsRules.cmake")
else()
  set(CMAKE_C_COMPILER "${HERMETIC_LLVM_BOOTSTRAP_BIN}/clang${_hb_exe}")
  set(CMAKE_CXX_COMPILER "${HERMETIC_LLVM_BOOTSTRAP_BIN}/clang++${_hb_exe}")
  set(CMAKE_ASM_COMPILER "${HERMETIC_LLVM_BOOTSTRAP_BIN}/clang${_hb_exe}")
endif()
set(CMAKE_AR "${HERMETIC_LLVM_BOOTSTRAP_BIN}/llvm-ar${_hb_exe}" CACHE FILEPATH "")
set(CMAKE_RANLIB "${HERMETIC_LLVM_BOOTSTRAP_BIN}/llvm-ranlib${_hb_exe}" CACHE FILEPATH "")
set(CMAKE_NM "${HERMETIC_LLVM_BOOTSTRAP_BIN}/llvm-nm${_hb_exe}" CACHE FILEPATH "")
set(CMAKE_OBJCOPY "${HERMETIC_LLVM_BOOTSTRAP_BIN}/llvm-objcopy${_hb_exe}" CACHE FILEPATH "")
set(CMAKE_STRIP "${HERMETIC_LLVM_BOOTSTRAP_BIN}/llvm-strip${_hb_exe}" CACHE FILEPATH "")
if(_hb_windows)
  set(CMAKE_LINKER "${HERMETIC_LLVM_BOOTSTRAP_BIN}/lld-link${_hb_exe}" CACHE FILEPATH "")
else()
  set(CMAKE_LINKER "${HERMETIC_LLVM_BOOTSTRAP_BIN}/ld.lld${_hb_exe}" CACHE FILEPATH "")
endif()
set(CMAKE_C_COMPILER_AR "${CMAKE_AR}")
set(CMAKE_CXX_COMPILER_AR "${CMAKE_AR}")
set(CMAKE_C_COMPILER_RANLIB "${CMAKE_RANLIB}")
set(CMAKE_CXX_COMPILER_RANLIB "${CMAKE_RANLIB}")
foreach(_hb_lang C CXX ASM)
  set(CMAKE_${_hb_lang}_COMPILER_TARGET "${HERMETIC_LLVM_BOOTSTRAP_TRIPLE}")
endforeach()
if(HERMETIC_LLVM_BOOTSTRAP_SYSROOT)
  set(CMAKE_SYSROOT "${HERMETIC_LLVM_BOOTSTRAP_SYSROOT}")
endif()
set(_hb_flags "${HERMETIC_LLVM_BOOTSTRAP_EXTRA_FLAGS} ${HERMETIC_LLVM_BOOTSTRAP_PREFIX_MAP}")
if(HERMETIC_LLVM_BOOTSTRAP_RESOURCE_DIR)
  string(APPEND _hb_flags " -resource-dir=${HERMETIC_LLVM_BOOTSTRAP_RESOURCE_DIR}")
endif()
foreach(_hb_lang C CXX ASM)
  set(CMAKE_${_hb_lang}_FLAGS_INIT "${_hb_flags}")
endforeach()
set(CMAKE_CXX_FLAGS_INIT "${HERMETIC_LLVM_BOOTSTRAP_CXX_FIRST_FLAGS} ${_hb_flags} ${HERMETIC_LLVM_BOOTSTRAP_EXTRA_CXX_FLAGS}")
set(CMAKE_CXX_STANDARD_LIBRARIES_INIT "${HERMETIC_LLVM_BOOTSTRAP_CXX_LIBS}")
if(_hb_windows)
  # lld-link is invoked directly by CMake's MSVC-style rules.
  set(CMAKE_EXE_LINKER_FLAGS_INIT "${HERMETIC_LLVM_BOOTSTRAP_LINK_FLAGS}")
  set(CMAKE_SHARED_LINKER_FLAGS_INIT "${HERMETIC_LLVM_BOOTSTRAP_LINK_FLAGS}")
  set(CMAKE_MODULE_LINKER_FLAGS_INIT "${HERMETIC_LLVM_BOOTSTRAP_LINK_FLAGS}")
else()
  set(CMAKE_EXE_LINKER_FLAGS_INIT "-fuse-ld=lld ${_hb_flags} ${HERMETIC_LLVM_BOOTSTRAP_LINK_FLAGS}")
  set(CMAKE_SHARED_LINKER_FLAGS_INIT "-fuse-ld=lld ${_hb_flags} ${HERMETIC_LLVM_BOOTSTRAP_LINK_FLAGS}")
  set(CMAKE_MODULE_LINKER_FLAGS_INIT "-fuse-ld=lld ${_hb_flags} ${HERMETIC_LLVM_BOOTSTRAP_LINK_FLAGS}")
endif()
if(NOT HERMETIC_LLVM_BOOTSTRAP_LINK_TESTS)
  set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
endif()
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
