# Copyright 2026 The hermetic-llvm-cmake Authors.
# SPDX-License-Identifier: Apache-2.0
#
# Prints what the toolchain knows about: options, targets, libc versions,
# compiler prebuilts and prebuilt runtime sets.
#
#   cmake -P scripts/help.cmake
#   cmake -DTOPIC=<options|targets|libcs|compilers|runtimes|windows> -P scripts/help.cmake

cmake_minimum_required(VERSION 3.19)
get_filename_component(HERMETIC_LLVM_DIR "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
include("${HERMETIC_LLVM_DIR}/cmake/HermeticLLVMCommon.cmake")
include("${HERMETIC_LLVM_DIR}/cmake/HermeticLLVMDistributions.cmake")
include("${HERMETIC_LLVM_DIR}/cmake/HermeticLLVMTargets.cmake")
include("${HERMETIC_LLVM_DIR}/cmake/HermeticLLVMConfigure.cmake")
include("${HERMETIC_LLVM_DIR}/cmake/HermeticLLVMRuntimes.cmake")
include("${HERMETIC_LLVM_DIR}/cmake/HermeticLLVMWindows.cmake")

if(NOT DEFINED TOPIC OR TOPIC STREQUAL "")
  set(TOPIC all)
endif()
function(out)
  message("${ARGN}")
endfunction()
hermetic_llvm_load_runtime_sources()

if(TOPIC MATCHES "^(all|options)$")
  out("Usage:")
  out("  cmake -S <src> -B <build> -DCMAKE_TOOLCHAIN_FILE=${HERMETIC_LLVM_DIR}/toolchain.cmake [options]")
  out("  cmake [options] -P ${HERMETIC_LLVM_DIR}/scripts/prefetch.cmake          fetch/build ahead of time (-DHERMETIC_LLVM_DRY_RUN=ON only prints)")
  out("  cmake [options] -P ${HERMETIC_LLVM_DIR}/runtimes/build_runtimes.cmake   build (and -DHERMETIC_LLVM_PACKAGE=ON package) a runtime set")
  out("  cmake -DTOPIC=<options|targets|libcs|compilers|runtimes|windows> -P ${HERMETIC_LLVM_DIR}/scripts/help.cmake")
  out("")
  out("Options (all -D cache variables):")
  out("  HERMETIC_LLVM_VERSION=<X.Y.Z|latest|first|latest:>=22,<23>   LLVM version (default: latest)")
  out("  HERMETIC_LLVM_RELEASE=<llvm-23.1.0-3>                          pin a hermeticbuild release id instead")
  out("  HERMETIC_LLVM_TARGET=<target>                                  platform to build for (default: host); see targets")
  out("  HERMETIC_LLVM_LIBC=<gnu.X.Y|musl>                              Linux libc (default: ${HERMETIC_LLVM_DEFAULT_LIBC}); see libcs")
  out("  HERMETIC_LLVM_CXX_STDLIB=<libc++|msvc>                          C++ library; Windows targets default to the MSVC STL, libc++ builds a runtime set")
  out("  HERMETIC_LLVM_RUNTIMES=<auto|download|build>                   prebuilt runtime set if listed, else build locally (default: auto)")
  out("  HERMETIC_LLVM_RUNTIME_SET_DIR=<dir>                            use an existing runtime set")
  out("  HERMETIC_LLVM_RUNTIME_SETS_FILES=<json>;...                    extra prebuilt runtime set indexes")
  out("  HERMETIC_LLVM_RUNTIME_SANITIZERS=ON                            build sanitizer runtimes into the set")
  out("  HERMETIC_LLVM_PIE=<ON|OFF>                                     musl: -static-pie / -static; glibc: default / -no-pie")
  out("  HERMETIC_LLVM_SYSROOT=<sdk|dir|url|none>                        macOS SDK, or a bring-your-own sysroot (disables runtime sets)")
  out("  HERMETIC_LLVM_ACCEPT_MICROSOFT_EULA=1                            required for Windows targets (MSVC runtime + Windows SDK downloads)")
  out("  HERMETIC_LLVM_MSVC_VERSION=<14.x.y|latest|default>               MSVC toolset for Windows targets; see windows")
  out("  HERMETIC_LLVM_WINDOWS_SDK_VERSION=<10.0.x.y|10.0.x|latest|default>  Windows SDK for Windows targets; see windows")
  out("  HERMETIC_LLVM_SYSROOT_SHA256 / _STRIP_COMPONENTS                for a URL sysroot")
  out("  HERMETIC_LLVM_DISTRIBUTION_URL / _SHA256 / _STRIP_COMPONENTS    bring your own compiler archive")
  out("  HERMETIC_LLVM_HERMETICBUILD_INDEX=<json>                        another copy of the compiler prebuilt index")
  out("  HERMETIC_LLVM_MIRROR_URLS=<template>;...                        mirrors ({version}, {release}, {basename})")
  out("  HERMETIC_LLVM_EMULATOR=<cmd;args>                               CMAKE_CROSSCOMPILING_EMULATOR for tests")
  out("  HERMETIC_LLVM_USE_LLD=ON  HERMETIC_LLVM_REPRODUCIBLE=ON")
  out("  HERMETIC_LLVM_EXTRA_COMPILE_FLAGS / _EXTRA_CXX_FLAGS / _EXTRA_LINK_FLAGS / _EXTRA_LINK_LIBS")
  out("  HERMETIC_LLVM_CACHE_DIR=<dir>  HERMETIC_LLVM_KEEP_ARCHIVES=OFF  HERMETIC_LLVM_KEEP_BUILD_DIRS=OFF  HERMETIC_LLVM_SHOW_PROGRESS=OFF  HERMETIC_LLVM_VERBOSE=OFF")
  out("")
endif()

if(TOPIC MATCHES "^(all|targets)$")
  hermetic_llvm_detect_host(host_os host_arch)
  out("Host: ${host_os}-${host_arch}")
  out("")
  out("Targets (HERMETIC_LLVM_TARGET):")
  foreach(key IN LISTS HERMETIC_LLVM_SUPPORTED_TARGETS)
    hermetic_llvm_target_info("${key}" t)
    set(notes "")
    if("${t_OS}-${t_ARCH}" STREQUAL "${host_os}-${host_arch}")
      set(notes "host")
    endif()
    if(t_OS STREQUAL "linux")
      hermetic_llvm_libc_triple("${t_ARCH}" gnu gnu_triple)
      hermetic_llvm_libc_triple("${t_ARCH}" musl musl_triple)
      set(triples "${gnu_triple} / ${musl_triple}")
    else()
      set(triples "${t_TRIPLE}")
    endif()
    string(LENGTH "${key}" len)
    math(EXPR pad "16 - ${len}")
    string(REPEAT " " ${pad} pad)
    out("  ${key}${pad}${triples}  (${t_SYSTEM_NAME}/${t_SYSTEM_PROCESSOR})  ${notes}")
  endforeach()
  out("")
endif()

if(TOPIC MATCHES "^(all|libcs)$")
  hermetic_llvm_glibc_versions(versions)
  string(JSON musl GET "${_HERMETIC_LLVM_RUNTIME_SOURCES}" "musl" "version")
  string(JSON musl_kernel GET "${_HERMETIC_LLVM_RUNTIME_SOURCES}" "musl" "kernel")
  out("Linux libcs (HERMETIC_LLVM_LIBC), default ${HERMETIC_LLVM_DEFAULT_LIBC}:")
  out("  musl          musl ${musl}, static-pie, Linux ${musl_kernel} UAPI headers")
  foreach(v IN LISTS versions)
    string(JSON kernel GET "${_HERMETIC_LLVM_RUNTIME_SOURCES}" "glibc" "${v}" "kernel")
    out("  gnu.${v}      glibc ${v} headers + symbol stubs, Linux ${kernel} UAPI headers")
  endforeach()
  out("")
endif()

if(TOPIC MATCHES "^(all|compilers)$")
  hermetic_llvm_load_hermeticbuild_index(hb)
  string(JSON default_version GET "${hb}" "default_prebuilt_llvm_version")
  string(JSON latest GET "${hb}" "latest_by_llvm_version")
  string(JSON releases GET "${hb}" "releases")
  out("Compiler prebuilts from hermeticbuild/hermetic-llvm (HERMETIC_LLVM_VERSION / HERMETIC_LLVM_RELEASE; their default is ${default_version}):")
  string(JSON n LENGTH "${latest}")
  set(hb_versions "")
  math(EXPR last "${n} - 1")
  foreach(i RANGE ${last})
    string(JSON v MEMBER "${latest}" ${i})
    list(APPEND hb_versions "${v}")
  endforeach()
  list(SORT hb_versions COMPARE NATURAL ORDER DESCENDING)
  foreach(v IN LISTS hb_versions)
    string(JSON rel GET "${latest}" "${v}")
    string(JSON entry GET "${releases}" "${rel}")
    string(JSON m LENGTH "${entry}")
    set(hosts "")
    math(EXPR mlast "${m} - 1")
    foreach(j RANGE ${mlast})
      string(JSON h MEMBER "${entry}" ${j})
      list(APPEND hosts "${h}")
    endforeach()
    string(REPLACE ";" "  " hosts "${hosts}")
    string(LENGTH "${v}" len)
    math(EXPR pad "12 - ${len}")
    string(REPEAT " " ${pad} pad)
    out("  ${v}${pad}${rel}   ${hosts}")
  endforeach()
  out("")
endif()

if(TOPIC MATCHES "^(all|windows)$")
  hermetic_llvm_windows_versions(msvc msvc_default sdk sdk_default)
  string(REPLACE ";" "  " msvc "${msvc}")
  string(REPLACE ";" "  " sdk "${sdk}")
  out("Windows targets (HERMETIC_LLVM_ACCEPT_MICROSOFT_EULA=1 required):")
  out("  MSVC toolsets (HERMETIC_LLVM_MSVC_VERSION), default ${msvc_default}:")
  out("    ${msvc}")
  out("  Windows SDKs (HERMETIC_LLVM_WINDOWS_SDK_VERSION), default ${sdk_default}; a build prefix such as 10.0.22621 picks its newest version:")
  out("    ${sdk}")
  out("  C++ library (HERMETIC_LLVM_CXX_STDLIB): msvc (the toolset's STL, default) or libc++ (static, Microsoft ABI, one")
  out("    archive per CRT flavour honouring CMAKE_MSVC_RUNTIME_LIBRARY, with compiler-rt builtins, in the runtime set <target>-msvc.<toolset>)")
  out("")
endif()

if(TOPIC MATCHES "^(all|runtimes)$")
  out("Prebuilt runtime sets (cmake/distributions/runtime_sets.json; others are built locally):")
  set(count 0)
  foreach(file IN ITEMS "${HERMETIC_LLVM_DIR}/cmake/distributions/runtime_sets.json" ${HERMETIC_LLVM_RUNTIME_SETS_FILES})
    hermetic_llvm_read_json("${file}" json)
    string(JSON n LENGTH "${json}")
    if(n EQUAL 0)
      continue()
    endif()
    math(EXPR last "${n} - 1")
    foreach(i RANGE ${last})
      string(JSON llvm MEMBER "${json}" ${i})
      string(JSON sets GET "${json}" "${llvm}")
      string(JSON m LENGTH "${sets}")
      math(EXPR mlast "${m} - 1")
      foreach(j RANGE ${mlast})
        string(JSON id MEMBER "${sets}" ${j})
        string(JSON url GET "${sets}" "${id}" "url")
        out("  ${llvm}  ${id}  ${url}")
        math(EXPR count "${count} + 1")
      endforeach()
    endforeach()
  endforeach()
  if(count EQUAL 0)
    out("  (none)")
  endif()
  hermetic_llvm_resolve_cache_dir()
  file(GLOB local LIST_DIRECTORIES true "${HERMETIC_LLVM_CACHE_DIR}/runtimes/*/*")
  set(local_sets "")
  foreach(d IN LISTS local)
    if(EXISTS "${d}/runtime-set.json")
      list(APPEND local_sets "${d}")
    endif()
  endforeach()
  if(local_sets)
    out("Runtime sets in ${HERMETIC_LLVM_CACHE_DIR}/runtimes:")
    foreach(d IN LISTS local_sets)
      file(RELATIVE_PATH rel "${HERMETIC_LLVM_CACHE_DIR}/runtimes" "${d}")
      out("  ${rel}")
    endforeach()
  endif()
  out("")
endif()
