# Copyright 2026 The hermetic-cpp-cmake Authors.
# SPDX-License-Identifier: Apache-2.0
#
# Downloads the compiler and prepares the runtime set a configuration would
# use, without configuring a project. Handy for warming caches:
#
#   cmake -DHERMETIC_LLVM_VERSION=23.1.0 -DHERMETIC_TARGET=linux-aarch64 \
#         -DHERMETIC_LIBC=musl -P scripts/prefetch.cmake
#
# Accepts the same HERMETIC_LLVM_* options as toolchain.cmake, plus
# -DHERMETIC_DRY_RUN=ON to only print what would be selected.

cmake_minimum_required(VERSION 3.19)
get_filename_component(HERMETIC_DIR "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
if(NOT DEFINED HERMETIC_LLVM_VERSION OR HERMETIC_LLVM_VERSION STREQUAL "")
  set(HERMETIC_LLVM_VERSION "latest")
endif()
include("${HERMETIC_DIR}/cmake/HermeticCommon.cmake")
include("${HERMETIC_DIR}/cmake/HermeticDistributions.cmake")
include("${HERMETIC_DIR}/cmake/HermeticTargets.cmake")
include("${HERMETIC_DIR}/cmake/HermeticConfigure.cmake")
include("${HERMETIC_DIR}/cmake/HermeticLLVMRuntimes.cmake")
include("${HERMETIC_DIR}/cmake/HermeticWindows.cmake")
include("${HERMETIC_DIR}/cmake/HermeticDarwin.cmake")
include("${HERMETIC_DIR}/cmake/HermeticResolve.cmake")

if(HERMETIC_DRY_RUN)
  hermetic_detect_host(host_os host_arch)
  if(NOT DEFINED HERMETIC_TARGET OR HERMETIC_TARGET STREQUAL "" OR HERMETIC_TARGET STREQUAL "host")
    set(HERMETIC_TARGET "${host_os}-${host_arch}")
  endif()
  hermetic_target_info("${HERMETIC_TARGET}" tgt)
  hermetic_resolve_cache_dir()
  hermetic_llvm_load_runtime_sources()
  hermetic_llvm_select_hermeticbuild("${HERMETIC_LLVM_VERSION}" "${host_os}" "${host_arch}" sel)
  message(STATUS "host:      ${host_os}-${host_arch}")
  message(STATUS "llvm:      ${sel_VERSION} ${sel_KEY} [${sel_RELEASE}]")
  message(STATUS "sha256:    ${sel_SHA256}")
  message(STATUS "urls:      ${sel_URLS}")
  if(tgt_OS STREQUAL "linux")
    if(NOT HERMETIC_LIBC)
      set(HERMETIC_LIBC "${HERMETIC_DEFAULT_LIBC}")
    endif()
    hermetic_parse_libc("${HERMETIC_LIBC}" family version)
    hermetic_libc_triple("${tgt_ARCH}" "${family}" triple)
    message(STATUS "target:    ${HERMETIC_TARGET} (${triple})")
    message(STATUS "runtimes:  ${HERMETIC_TARGET}-${HERMETIC_LIBC} in ${HERMETIC_CACHE_DIR}/runtimes/${sel_VERSION}/")
  elseif(tgt_OS STREQUAL "windows" AND HERMETIC_WINDOWS_ABI STREQUAL "gnu")
    hermetic_windows_gnu_triple("${tgt_ARCH}" triple)
    message(STATUS "target:    ${HERMETIC_TARGET} (${triple}), MinGW-w64")
    message(STATUS "runtimes:  ${HERMETIC_TARGET}-mingw in ${HERMETIC_CACHE_DIR}/runtimes/${sel_VERSION}/")
  elseif(tgt_OS STREQUAL "windows" AND HERMETIC_CXX_STDLIB STREQUAL "libc++")
    hermetic_windows_versions(msvc msvc_default sdk sdk_default)
    hermetic_llvm_select_version("MSVC toolset (HERMETIC_MSVC_TOOLSET_VERSION)" "${HERMETIC_MSVC_TOOLSET_VERSION}" "${msvc_default}" "${msvc}" msvc_version)
    message(STATUS "target:    ${HERMETIC_TARGET} (${tgt_TRIPLE}), libc++")
    message(STATUS "runtimes:  ${HERMETIC_TARGET}-msvc.${msvc_version} in ${HERMETIC_CACHE_DIR}/runtimes/${sel_VERSION}/")
  elseif(tgt_OS STREQUAL "wasm")
    message(STATUS "target:    ${HERMETIC_TARGET} (${tgt_TRIPLE}), freestanding")
    message(STATUS "runtimes:  ${HERMETIC_TARGET}-none in ${HERMETIC_CACHE_DIR}/runtimes/${sel_VERSION}/")
  elseif(tgt_OS STREQUAL "darwin" AND (NOT HERMETIC_SYSROOT OR HERMETIC_SYSROOT MATCHES "^(default|sdk)$"))
    hermetic_macos_sdk_versions(versions default)
    hermetic_llvm_select_version("macOS SDK (HERMETIC_MACOS_SDK_VERSION)" "${HERMETIC_MACOS_SDK_VERSION}" "${default}" "${versions}" sdk_version)
    message(STATUS "target:    ${HERMETIC_TARGET} (${tgt_TRIPLE})")
    message(STATUS "macOS SDK: ${sdk_version} in ${HERMETIC_CACHE_DIR}/macos/")
  else()
    message(STATUS "target:    ${HERMETIC_TARGET} (${tgt_TRIPLE})")
  endif()
  message(STATUS "cache dir: ${HERMETIC_CACHE_DIR}")
else()
  hermetic_resolve()
endif()
