# Copyright 2026 The hermetic-llvm-cmake Authors.
# SPDX-License-Identifier: Apache-2.0
#
# Compiler prebuilt selection: the hermeticbuild/hermetic-llvm
# "llvm-toolchain-minimal" index, version requirements, and bring-your-own
# archives.

include_guard(GLOBAL)

# Extracts the LLVM version ("20.1.8", "21.1.0-rc3") from an archive name/URL.
function(hermetic_llvm_parse_archive_version KEY OUT_VERSION)
  string(REGEX REPLACE "[?#].*$" "" name "${KEY}")
  get_filename_component(name "${name}" NAME)
  string(REPLACE "%2B" "+" name "${name}")
  if(name MATCHES "^(LLVM|clang\\+llvm)-([0-9]+\\.[0-9]+\\.[0-9]+(-rc[0-9]+)?)-")
    set(${OUT_VERSION} "${CMAKE_MATCH_2}" PARENT_SCOPE)
  else()
    set(${OUT_VERSION} "" PARENT_SCOPE)
  endif()
endfunction()

# Splits "20.1.8-rc3" into core "20.1.8" and prerelease "rc3" (or "").
function(hermetic_llvm_split_version VERSION OUT_CORE OUT_PRE)
  if(VERSION MATCHES "^([0-9]+\\.[0-9]+\\.[0-9]+)(-(.+))?$")
    set(${OUT_CORE} "${CMAKE_MATCH_1}" PARENT_SCOPE)
    set(${OUT_PRE} "${CMAKE_MATCH_3}" PARENT_SCOPE)
  else()
    set(${OUT_CORE} "" PARENT_SCOPE)
    set(${OUT_PRE} "" PARENT_SCOPE)
  endif()
endfunction()

# Parses a version requirement: exact ("20.1.8"), "latest", "first",
# "latest:>=17,<20", "first:>=15.0.6,<16".
function(hermetic_llvm_parse_requirement SPEC OUT_MODE OUT_CONDITIONS)
  if(SPEC MATCHES "^(latest|first)(:(.*))?$")
    set(${OUT_MODE} "${CMAKE_MATCH_1}" PARENT_SCOPE)
    string(REPLACE "," ";" conditions "${CMAKE_MATCH_3}")
    set(${OUT_CONDITIONS} "${conditions}" PARENT_SCOPE)
  elseif(SPEC MATCHES "^[0-9]+\\.[0-9]+\\.[0-9]+(-rc[0-9]+)?$")
    set(${OUT_MODE} "exact" PARENT_SCOPE)
    set(${OUT_CONDITIONS} "" PARENT_SCOPE)
  else()
    hermetic_llvm_fatal("Invalid HERMETIC_LLVM_VERSION '${SPEC}': expected X.Y.Z[-rcN], latest[:cond,...] or first[:cond,...]")
  endif()
endfunction()

# TRUE in ${OUT} when CORE (X.Y.Z) satisfies every condition (<, <=, >, >=, ==, !=).
function(hermetic_llvm_version_satisfies CORE CONDITIONS OUT)
  set(ok TRUE)
  foreach(cond IN LISTS CONDITIONS)
    string(STRIP "${cond}" cond)
    if(cond STREQUAL "")
      continue()
    endif()
    if(NOT cond MATCHES "^(<=|>=|==|!=|<|>)([0-9]+(\\.[0-9]+)*)$")
      hermetic_llvm_fatal("Invalid version condition '${cond}'")
    endif()
    set(op "${CMAKE_MATCH_1}")
    set(rhs "${CMAKE_MATCH_2}")
    if(op STREQUAL "<" AND NOT CORE VERSION_LESS rhs)
      set(ok FALSE)
    elseif(op STREQUAL "<=" AND NOT CORE VERSION_LESS_EQUAL rhs)
      set(ok FALSE)
    elseif(op STREQUAL ">" AND NOT CORE VERSION_GREATER rhs)
      set(ok FALSE)
    elseif(op STREQUAL ">=" AND NOT CORE VERSION_GREATER_EQUAL rhs)
      set(ok FALSE)
    elseif(op STREQUAL "==" AND NOT CORE VERSION_EQUAL rhs)
      set(ok FALSE)
    elseif(op STREQUAL "!=" AND CORE VERSION_EQUAL rhs)
      set(ok FALSE)
    endif()
  endforeach()
  set(${OUT} ${ok} PARENT_SCOPE)
endfunction()

# ---- hermeticbuild/hermetic-llvm compiler prebuilts ------------------------
# The index (cmake/distributions/hermeticbuild.json) is a verbatim copy of
# extensions/llvm_toolchain_minimal_index.json from that project:
#   { "default_prebuilt_llvm_version": "...",
#     "latest_by_llvm_version": {"<version>": "<release id>"},
#     "releases": {"<release id>": {"<host key>": {"url": ..., "sha256": ...}}} }
# The archives contain bin/ and lib/clang/<N>/ only (no runtime libraries).

# Maps (OS, ARCH) to the host key used in the hermeticbuild index.
function(hermetic_llvm_hermeticbuild_host_key OS ARCH OUT)
  set(key "")
  if(OS STREQUAL "darwin")
    if(ARCH STREQUAL "aarch64")
      set(key darwin-arm64)
    elseif(ARCH STREQUAL "x86_64")
      set(key darwin-amd64)
    endif()
  elseif(OS STREQUAL "linux")
    # Static musl builds run on any Linux distribution.
    if(ARCH STREQUAL "aarch64")
      set(key linux-arm64-musl)
    elseif(ARCH STREQUAL "x86_64")
      set(key linux-amd64-musl)
    endif()
  elseif(OS STREQUAL "windows")
    if(ARCH STREQUAL "aarch64")
      set(key windows-arm64)
    elseif(ARCH STREQUAL "x86_64")
      set(key windows-amd64)
    endif()
  endif()
  set(${OUT} "${key}" PARENT_SCOPE)
endfunction()

# Loads the hermeticbuild index (builtin file or HERMETIC_LLVM_HERMETICBUILD_INDEX).
function(hermetic_llvm_load_hermeticbuild_index OUT_JSON)
  set(file "${HERMETIC_LLVM_DIR}/cmake/distributions/hermeticbuild.json")
  if(HERMETIC_LLVM_HERMETICBUILD_INDEX)
    set(file "${HERMETIC_LLVM_HERMETICBUILD_INDEX}")
  endif()
  hermetic_llvm_read_json("${file}" json)
  set(${OUT_JSON} "${json}" PARENT_SCOPE)
endfunction()

# Selects a hermeticbuild compiler prebuilt for (OS, ARCH) satisfying SPEC
# (or the release id in HERMETIC_LLVM_RELEASE). Sets ${OUT}_KEY, _SHA256,
# _VERSION, _URLS, _RELEASE.
function(hermetic_llvm_select_hermeticbuild SPEC OS ARCH OUT)
  hermetic_llvm_load_hermeticbuild_index(json)
  hermetic_llvm_hermeticbuild_host_key("${OS}" "${ARCH}" host_key)
  if(NOT host_key)
    hermetic_llvm_fatal("hermeticbuild publishes no compiler prebuilt for host ${OS}-${ARCH}; use HERMETIC_LLVM_PROVIDER=upstream or HERMETIC_LLVM_DISTRIBUTION_URL")
  endif()
  string(JSON releases GET "${json}" "releases")

  set(release "")
  if(HERMETIC_LLVM_RELEASE)
    set(release "${HERMETIC_LLVM_RELEASE}")
    string(JSON entry ERROR_VARIABLE err GET "${releases}" "${release}")
    if(err)
      hermetic_llvm_fatal("HERMETIC_LLVM_RELEASE '${release}' is not in the hermeticbuild index")
    endif()
    if(NOT release MATCHES "^llvm-([0-9]+\\.[0-9]+\\.[0-9]+(-rc[0-9]+)?)-[0-9]+$")
      hermetic_llvm_fatal("Cannot derive the LLVM version from release id '${release}'")
    endif()
    set(version "${CMAKE_MATCH_1}")
  else()
    hermetic_llvm_parse_requirement("${SPEC}" mode conditions)
    string(JSON latest GET "${json}" "latest_by_llvm_version")
    string(JSON n LENGTH "${latest}")
    set(versions "")
    if(n GREATER 0)
      math(EXPR last "${n} - 1")
      foreach(i RANGE ${last})
        string(JSON v MEMBER "${latest}" ${i})
        string(JSON rel GET "${latest}" "${v}")
        string(JSON entry ERROR_VARIABLE err GET "${releases}" "${rel}" "${host_key}")
        if(err)
          continue()
        endif()
        hermetic_llvm_split_version("${v}" core pre)
        if(mode STREQUAL "exact")
          if(NOT v STREQUAL SPEC)
            continue()
          endif()
        else()
          if(pre)
            continue()
          endif()
          hermetic_llvm_version_satisfies("${core}" "${conditions}" ok)
          if(NOT ok)
            continue()
          endif()
        endif()
        list(APPEND versions "${v}")
        set(_release_${v} "${rel}")
      endforeach()
    endif()
    if(NOT versions)
      hermetic_llvm_fatal("No hermeticbuild compiler prebuilt matches version '${SPEC}' for host ${OS}-${ARCH}; see 'cmake -P scripts/help.cmake', or use HERMETIC_LLVM_PROVIDER=upstream")
    endif()
    list(SORT versions COMPARE NATURAL ORDER DESCENDING)
    if(mode STREQUAL "first")
      list(GET versions -1 version)
    else()
      list(GET versions 0 version)
    endif()
    set(release "${_release_${version}}")
  endif()

  string(JSON url GET "${releases}" "${release}" "${host_key}" "url")
  string(JSON sha GET "${releases}" "${release}" "${host_key}" "sha256")
  string(REGEX REPLACE "[?#].*$" "" key "${url}")
  get_filename_component(key "${key}" NAME)
  set(urls "${url}")
  foreach(mirror IN LISTS HERMETIC_LLVM_MIRROR_URLS)
    string(REPLACE "{version}" "${version}" m "${mirror}")
    string(REPLACE "{llvm_version}" "${version}" m "${m}")
    string(REPLACE "{release}" "${release}" m "${m}")
    string(REPLACE "{basename}" "${key}" m "${m}")
    list(APPEND urls "${m}")
  endforeach()
  set(${OUT}_KEY "${key}" PARENT_SCOPE)
  set(${OUT}_SHA256 "${sha}" PARENT_SCOPE)
  set(${OUT}_VERSION "${version}" PARENT_SCOPE)
  set(${OUT}_URLS "${urls}" PARENT_SCOPE)
  set(${OUT}_RELEASE "${release}" PARENT_SCOPE)
endfunction()

# Resolves the compiler for the host and makes sure it is extracted.
# Sets ${OUT}_ROOT, ${OUT}_VERSION, ${OUT}_RELEASE.
function(hermetic_llvm_provide_compiler SPEC OS ARCH OUT)
  set(release "")
  if(HERMETIC_LLVM_DISTRIBUTION_URL)
    if(NOT HERMETIC_LLVM_DISTRIBUTION_SHA256)
      hermetic_llvm_fatal("HERMETIC_LLVM_DISTRIBUTION_SHA256 is required with HERMETIC_LLVM_DISTRIBUTION_URL")
    endif()
    set(urls "${HERMETIC_LLVM_DISTRIBUTION_URL}")
    set(sha "${HERMETIC_LLVM_DISTRIBUTION_SHA256}")
    string(REGEX REPLACE "[?#].*$" "" name "${HERMETIC_LLVM_DISTRIBUTION_URL}")
    get_filename_component(name "${name}" NAME)
    hermetic_llvm_parse_archive_version("${name}" version)
    if(NOT version AND SPEC MATCHES "^[0-9]")
      set(version "${SPEC}")
    endif()
    set(strip "${HERMETIC_LLVM_DISTRIBUTION_STRIP_COMPONENTS}")
    if(strip STREQUAL "")
      set(strip 0)
    endif()
  else()
    hermetic_llvm_select_hermeticbuild("${SPEC}" "${OS}" "${ARCH}" sel)
    set(urls "${sel_URLS}")
    set(sha "${sel_SHA256}")
    set(version "${sel_VERSION}")
    set(name "${sel_KEY}")
    set(release "${sel_RELEASE}")
    set(strip 0)  # bin/ and lib/ at the archive root
  endif()
  string(REGEX REPLACE "\\.(tar\\.(xz|gz|zst|bz2)|tgz|zip)$" "" dirname "${name}")
  hermetic_llvm_fetch_archive(NAME "${dirname}" KIND llvm SHA256 "${sha}" URLS ${urls} STRIP_COMPONENTS ${strip} OUT_DIR root)
  if(NOT EXISTS "${root}/bin/clang${HERMETIC_LLVM_HOST_EXE}" AND NOT EXISTS "${root}/bin/clang")
    hermetic_llvm_fatal("Extracted compiler ${root} has no bin/clang; check HERMETIC_LLVM_DISTRIBUTION_STRIP_COMPONENTS")
  endif()
  set(${OUT}_ROOT "${root}" PARENT_SCOPE)
  set(${OUT}_VERSION "${version}" PARENT_SCOPE)
  set(${OUT}_RELEASE "${release}" PARENT_SCOPE)
endfunction()
