# Copyright 2026 The hermetic-cpp-cmake Authors.
# SPDX-License-Identifier: Apache-2.0
#
# The macOS SDK for macOS targets, downloaded from Apple's software update
# CDN: the SDK package of the Command Line Tools (CLTools_macOS*_SDK.pkg,
# listed in cmake/distributions/macos_sdk.json) expanded with pkgutil from
# the hermetic-llvm extras prebuilt, so every host gets the same SDK without
# Xcode. Its license (the Xcode and Apple SDKs Agreement) is Apple's; set
# HERMETIC_ACCEPT_APPLE_SDK_LICENSE=1 (variable or environment) to
# confirm. Only macOS SDKs are available this way: the SDKs of the other
# Apple platforms ship inside Xcode, which Apple does not serve without an
# account.

include_guard(GLOBAL)

function(hermetic_check_apple_sdk_license)
  set(value "${HERMETIC_ACCEPT_APPLE_SDK_LICENSE}")
  if(NOT value AND DEFINED ENV{HERMETIC_ACCEPT_APPLE_SDK_LICENSE})
    set(value "$ENV{HERMETIC_ACCEPT_APPLE_SDK_LICENSE}")
  endif()
  string(TOLOWER "${value}" value)
  if(NOT value MATCHES "^(1|on|yes|y|true)$")
    hermetic_fatal("Building for macOS downloads the macOS SDK from Apple's Command Line Tools package, whose license you must be entitled to (the Xcode and Apple SDKs Agreement, https://www.apple.com/legal/sla/docs/xcode.pdf, which limits its use to Apple-branded computers). Set HERMETIC_ACCEPT_APPLE_SDK_LICENSE=1 to confirm and let the toolchain download it, or HERMETIC_SYSROOT=host on a macOS host to use the SDK of the installed Xcode or Command Line Tools.")
  endif()
endfunction()

# Lists the SDK versions of the table and its default.
function(hermetic_macos_sdk_versions OUT_VERSIONS OUT_DEFAULT)
  hermetic_read_json("${HERMETIC_DIR}/cmake/distributions/macos_sdk.json" json)
  string(JSON sdks GET "${json}" "sdks")
  string(JSON n LENGTH "${sdks}")
  set(versions "")
  if(n GREATER 0)
    math(EXPR last "${n} - 1")
    foreach(i RANGE ${last})
      string(JSON v MEMBER "${sdks}" ${i})
      list(APPEND versions "${v}")
    endforeach()
  endif()
  string(JSON default GET "${json}" "default")
  set(${OUT_VERSIONS} "${versions}" PARENT_SCOPE)
  set(${OUT_DEFAULT} "${default}" PARENT_SCOPE)
endfunction()

# Sets ${OUT_NOTE} to the table's note about SDK VERSION, if any.
function(hermetic_macos_sdk_note VERSION OUT_NOTE)
  hermetic_read_json("${HERMETIC_DIR}/cmake/distributions/macos_sdk.json" json)
  string(JSON note ERROR_VARIABLE err GET "${json}" "sdks" "${VERSION}" "note")
  if(err)
    set(note "")
  endif()
  set(${OUT_NOTE} "${note}" PARENT_SCOPE)
endfunction()

# Sets ${OUT} to TRUE when the compiler under COMPILER_ROOT can link against
# SDK VERSION: the table lists the TextAPI targets of an SDK's library stubs
# that older linkers reject (requires_tapi_targets), and the prebuilt's
# llvm-readtapi, which shares ld64.lld's TextAPI reader, is asked to read a
# stub listing them.
function(hermetic_macos_sdk_usable VERSION COMPILER_ROOT OUT)
  set(${OUT} TRUE PARENT_SCOPE)
  hermetic_read_json("${HERMETIC_DIR}/cmake/distributions/macos_sdk.json" json)
  string(JSON targets ERROR_VARIABLE err GET "${json}" "sdks" "${VERSION}" "requires_tapi_targets")
  if(err)
    return()
  endif()
  string(JSON n LENGTH "${targets}")
  if(n EQUAL 0)
    return()
  endif()
  math(EXPR last "${n} - 1")
  set(list "")
  foreach(i RANGE ${last})
    string(JSON t GET "${targets}" ${i})
    list(APPEND list "${t}")
  endforeach()
  string(REPLACE ";" ", " list "${list}")
  set(${OUT} FALSE PARENT_SCOPE)
  hermetic_host_executable("${COMPILER_ROOT}/bin/llvm-readtapi" readtapi)
  if(NOT EXISTS "${readtapi}")
    return()
  endif()
  string(RANDOM LENGTH 8 id)
  set(stub "${HERMETIC_CACHE_DIR}/build/tapi-probe-${id}.tbd")
  file(WRITE "${stub}" "--- !tapi-tbd\ntbd-version: 4\ntargets: [ ${list} ]\ninstall-name: '/usr/lib/libhermetic_llvm_probe.dylib'\n...\n")
  execute_process(COMMAND "${readtapi}" "${stub}" RESULT_VARIABLE rc OUTPUT_QUIET ERROR_QUIET)
  file(REMOVE "${stub}")
  if(rc EQUAL 0)
    set(${OUT} TRUE PARENT_SCOPE)
  endif()
endfunction()

# Provides the macOS SDK selected by SPEC (an exact version, a prefix such
# as 15 for its newest listed version, latest, or default) and sets
# ${OUT_DIR} to its directory (<cache>/macos/MacOSX<version>.sdk). With
# COMPILER_ROOT, SDKs that compiler cannot link against are left out of the
# choice (see hermetic_macos_sdk_usable): the default and latest select
# the newest usable one, an exact version or a prefix fails.
function(hermetic_provide_macos_sdk SPEC OUT_DIR)
  cmake_parse_arguments(arg "" "COMPILER_ROOT" "" ${ARGN})
  hermetic_check_apple_sdk_license()
  hermetic_macos_sdk_versions(versions default)
  set(what "macOS SDK (HERMETIC_MACOS_SDK_VERSION)")
  hermetic_llvm_select_version("${what}" "${SPEC}" "${default}" "${versions}" version)
  if(arg_COMPILER_ROOT)
    hermetic_macos_sdk_usable("${version}" "${arg_COMPILER_ROOT}" usable)
    if(NOT usable)
      if(SPEC AND NOT SPEC MATCHES "^(default|latest)$")
        hermetic_fatal("The macOS ${version} SDK needs a newer compiler: its library stubs list targets the linker of ${arg_COMPILER_ROOT} does not read. Use a newer LLVM or another SDK version.")
      endif()
      set(usable_versions "")
      foreach(v IN LISTS versions)
        hermetic_macos_sdk_usable("${v}" "${arg_COMPILER_ROOT}" ok)
        if(ok)
          list(APPEND usable_versions "${v}")
        endif()
      endforeach()
      set(skipped "${version}")
      hermetic_llvm_select_version("${what}" latest "" "${usable_versions}" version)
      hermetic_log("macOS SDK ${skipped} needs a newer compiler; using ${version}")
    endif()
  endif()
  hermetic_read_json("${HERMETIC_DIR}/cmake/distributions/macos_sdk.json" json)
  string(JSON entry GET "${json}" "sdks" "${version}")
  string(JSON url GET "${entry}" "url")
  string(JSON sha GET "${entry}" "sha256")
  string(JSON prefix GET "${entry}" "prefix")
  set(urls "${url}")
  string(JSON mirrors ERROR_VARIABLE err GET "${entry}" "mirrors")
  if(NOT err)
    string(JSON m LENGTH "${mirrors}")
    if(m GREATER 0)
      math(EXPR last "${m} - 1")
      foreach(i RANGE ${last})
        string(JSON mirror GET "${mirrors}" ${i})
        list(APPEND urls "${mirror}")
      endforeach()
    endif()
  endif()
  set(name "MacOSX${version}.sdk")
  if(NOT EXISTS "${HERMETIC_CACHE_DIR}/macos/${name}/.hermetic-cpp.stamp")
    hermetic_log("Downloading the macOS ${version} SDK (Command Line Tools package, about 60 MB; expands to about 1 GB)")
  endif()
  # pkgutil from the extras prebuilt expands the package on every host.
  hermetic_fetch_extras(extras)
  hermetic_host_executable("${extras}/bin/pkgutil" pkgutil)
  hermetic_fetch_archive(NAME "${name}" KIND macos SHA256 "${sha}" URLS ${urls}
    PKGUTIL "${pkgutil}" PKG_PREFIX "${prefix}" OUT_DIR dir)
  foreach(probe usr/include/stdio.h usr/lib/libSystem.tbd usr/include/c++/v1/vector)
    if(NOT EXISTS "${dir}/${probe}")
      hermetic_fatal("The macOS ${version} SDK at ${dir} has no ${probe}; delete the directory to re-extract it")
    endif()
  endforeach()
  hermetic_log("macOS SDK ${version} at ${dir}")
  set(${OUT_DIR} "${dir}" PARENT_SCOPE)
endfunction()

# import std with the SDK's libc++: Apple ships its headers but not the
# module sources, which must come from the same libc++ release as the
# headers. The SDK names that release (_LIBCPP_VERSION, e.g. 220106 for
# 22.1.6); its module sources (libcxx/modules) are extracted from the LLVM
# source archive of that version, or of the newest listed release of the
# same major version, and generated into <cache>/macos/libcxx-modules-<v>
# as libc++'s own build installs them. Sets ${OUT} to the modules.json.
function(hermetic_macos_libcxx_modules SDK_DIR OUT)
  file(STRINGS "${SDK_DIR}/usr/include/c++/v1/__config" line REGEX "^#[ \t]*define[ \t]+_LIBCPP_VERSION[ \t]+[0-9]+")
  if(NOT line MATCHES "([0-9]+)([0-9][0-9])([0-9][0-9])$")
    hermetic_fatal("HERMETIC_MACOS_LIBCXX_MODULES: no libc++ version in ${SDK_DIR}/usr/include/c++/v1/__config")
  endif()
  math(EXPR minor "${CMAKE_MATCH_2}")
  math(EXPR patch "${CMAKE_MATCH_3}")
  set(sdk_libcxx "${CMAKE_MATCH_1}.${minor}.${patch}")
  hermetic_read_json("${HERMETIC_DIR}/cmake/distributions/llvm_sources.json" json)
  string(JSON n LENGTH "${json}")
  math(EXPR last "${n} - 1")
  set(chosen "")
  foreach(i RANGE ${last})
    string(JSON v MEMBER "${json}" ${i})
    if(v STREQUAL sdk_libcxx)
      set(chosen "${v}")
      break()
    endif()
    if(v MATCHES "^${CMAKE_MATCH_1}\\.[0-9]+\\.[0-9]+$" AND (NOT chosen OR v VERSION_GREATER chosen))
      set(chosen "${v}")
    endif()
  endforeach()
  if(NOT chosen)
    hermetic_fatal("HERMETIC_MACOS_LIBCXX_MODULES: the SDK's libc++ is ${sdk_libcxx}, and cmake/distributions/llvm_sources.json lists no LLVM ${CMAKE_MATCH_1}.x sources to take its module sources from; use an SDK whose libc++ has a listed release")
  endif()

  set(dir "${HERMETIC_CACHE_DIR}/macos/libcxx-modules-${chosen}")
  if(EXISTS "${dir}/libc++.modules.json")
    set(${OUT} "${dir}/libc++.modules.json" PARENT_SCOPE)
    return()
  endif()
  string(JSON url GET "${json}" "${chosen}" "url")
  string(JSON sha GET "${json}" "${chosen}" "sha256")
  get_filename_component(top "${url}" NAME)
  string(REGEX REPLACE "\\.tar\\.[a-z0-9]+$" "" top "${top}")
  hermetic_fetch_archive(NAME "llvm-project-${chosen}-libcxx-modules" KIND src SHA256 "${sha}" URLS "${url}"
    STRIP_COMPONENTS 1 PATTERNS "${top}/libcxx/modules" OUT_DIR src)
  set(modules "${src}/libcxx/modules")

  file(MAKE_DIRECTORY "${HERMETIC_CACHE_DIR}/locks")
  file(LOCK "${HERMETIC_CACHE_DIR}/locks/macos-libcxx-modules-${chosen}.lock" GUARD FUNCTION TIMEOUT 600)
  if(EXISTS "${dir}/libc++.modules.json")
    set(${OUT} "${dir}/libc++.modules.json" PARENT_SCOPE)
    return()
  endif()
  set(tmp "${dir}.tmp")
  file(REMOVE_RECURSE "${tmp}")
  file(MAKE_DIRECTORY "${tmp}")
  file(COPY "${modules}/std" "${modules}/std.compat" DESTINATION "${tmp}")
  # libcxx/modules/CMakeLists.txt lists the partitions each module includes.
  file(READ "${modules}/CMakeLists.txt" lists)
  foreach(module std std.compat)
    string(TOUPPER "${module}" var)
    string(REPLACE "." "_" var "${var}")
    if(NOT lists MATCHES "set\\(LIBCXX_MODULE_${var}_SOURCES([^)]*)\\)")
      hermetic_fatal("HERMETIC_MACOS_LIBCXX_MODULES: no LIBCXX_MODULE_${var}_SOURCES in ${modules}/CMakeLists.txt")
    endif()
    string(REGEX MATCHALL "[^ \t\r\n]+\\.inc" files "${CMAKE_MATCH_1}")
    set(LIBCXX_MODULE_${var}_INCLUDE_SOURCES "")
    foreach(file IN LISTS files)
      string(APPEND LIBCXX_MODULE_${var}_INCLUDE_SOURCES "#include \"${file}\"\n")
    endforeach()
    configure_file("${modules}/${module}.cppm.in" "${tmp}/${module}.cppm" @ONLY)
  endforeach()
  set(LIBCXX_MODULE_RELATIVE_PATH ".")
  configure_file("${modules}/modules.json.in" "${tmp}/libc++.modules.json" @ONLY)
  file(REMOVE_RECURSE "${dir}")
  file(RENAME "${tmp}" "${dir}")
  hermetic_log("libc++ ${chosen} module sources for the SDK's libc++ ${sdk_libcxx} at ${dir}")
  set(${OUT} "${dir}/libc++.modules.json" PARENT_SCOPE)
endfunction()
