# Copyright 2026 The hermetic-llvm-cmake Authors.
# SPDX-License-Identifier: Apache-2.0
#
# Shared helpers for the hermetic LLVM toolchain: logging, host detection,
# the download cache, and archive fetching/extraction with locking.

include_guard(GLOBAL)

# Environment fallbacks for options that CI systems set globally.
foreach(_hl_env HERMETIC_LLVM_KEEP_ARCHIVES HERMETIC_LLVM_KEEP_BUILD_DIRS HERMETIC_LLVM_SHOW_PROGRESS HERMETIC_LLVM_VERBOSE)
  if(NOT DEFINED ${_hl_env} AND DEFINED ENV{${_hl_env}})
    set(${_hl_env} "$ENV{${_hl_env}}")
  endif()
endforeach()

function(hermetic_llvm_log)
  message(STATUS "[hermetic-llvm] ${ARGN}")
endfunction()

function(hermetic_llvm_debug)
  if(HERMETIC_LLVM_VERBOSE)
    message(STATUS "[hermetic-llvm] ${ARGN}")
  endif()
endfunction()

function(hermetic_llvm_fatal)
  message(FATAL_ERROR "[hermetic-llvm] ${ARGN}")
endfunction()

# Sets ${OUT_OS} to one of linux/darwin/windows and ${OUT_ARCH} to one of
# x86_64/aarch64/armv7/riscv64 for the machine running CMake.
function(hermetic_llvm_detect_host OUT_OS OUT_ARCH)
  set(os "${CMAKE_HOST_SYSTEM_NAME}")
  if(NOT os)
    cmake_host_system_information(RESULT os QUERY OS_NAME)
  endif()
  if(os MATCHES "^(Darwin|macOS)$")
    set(os darwin)
  elseif(os STREQUAL "Linux")
    set(os linux)
  elseif(os MATCHES "^Windows")
    set(os windows)
  else()
    hermetic_llvm_fatal("Unsupported host OS: ${os}")
  endif()

  cmake_host_system_information(RESULT arch QUERY OS_PLATFORM)
  string(TOLOWER "${arch}" arch)
  if(arch MATCHES "^(arm64|aarch64)$")
    set(arch aarch64)
  elseif(arch MATCHES "^(x86_64|amd64|x64)$")
    set(arch x86_64)
  elseif(arch MATCHES "^armv7")
    set(arch armv7)
  elseif(arch STREQUAL "riscv64")
    set(arch riscv64)
  else()
    hermetic_llvm_fatal("Unsupported host architecture: ${arch}")
  endif()
  set(${OUT_OS} "${os}" PARENT_SCOPE)
  set(${OUT_ARCH} "${arch}" PARENT_SCOPE)
endfunction()

# Reads /etc/os-release on Linux hosts. Sets ${OUT_NAME} (ID, or a known
# ID_LIKE) and ${OUT_VERSION} (VERSION_ID), both possibly empty.
function(hermetic_llvm_detect_linux_distribution OUT_NAME OUT_VERSION)
  set(name "")
  set(version "")
  if(EXISTS /etc/os-release)
    file(STRINGS /etc/os-release lines)
    set(id "")
    set(id_like "")
    foreach(line IN LISTS lines)
      if(line MATCHES "^ID=\"?([^\"]*)\"?$")
        set(id "${CMAKE_MATCH_1}")
      elseif(line MATCHES "^ID_LIKE=\"?([^\"]*)\"?$")
        set(id_like "${CMAKE_MATCH_1}")
      elseif(line MATCHES "^VERSION_ID=\"?([^\"]*)\"?$")
        set(version "${CMAKE_MATCH_1}")
      endif()
    endforeach()
    set(known almalinux amzn arch centos debian fedora freebsd manjaro ol pop raspbian rhel suse ubuntu)
    set(name "${id}")
    if(NOT id IN_LIST known AND id_like)
      string(REPLACE " " ";" id_like "${id_like}")
      foreach(candidate IN LISTS id_like)
        if(candidate IN_LIST known)
          set(name "${candidate}")
          break()
        endif()
      endforeach()
    endif()
  endif()
  set(${OUT_NAME} "${name}" PARENT_SCOPE)
  set(${OUT_VERSION} "${version}" PARENT_SCOPE)
endfunction()

# Resolves the on-disk cache directory into HERMETIC_LLVM_CACHE_DIR.
function(hermetic_llvm_resolve_cache_dir)
  if(HERMETIC_LLVM_CACHE_DIR)
    set(dir "${HERMETIC_LLVM_CACHE_DIR}")
  elseif(DEFINED ENV{HERMETIC_LLVM_CACHE_DIR} AND NOT "$ENV{HERMETIC_LLVM_CACHE_DIR}" STREQUAL "")
    set(dir "$ENV{HERMETIC_LLVM_CACHE_DIR}")
  elseif(CMAKE_HOST_WIN32)
    set(dir "$ENV{LOCALAPPDATA}/hermetic-llvm")
  elseif(DEFINED ENV{XDG_CACHE_HOME} AND NOT "$ENV{XDG_CACHE_HOME}" STREQUAL "")
    set(dir "$ENV{XDG_CACHE_HOME}/hermetic-llvm")
  else()
    set(dir "$ENV{HOME}/.cache/hermetic-llvm")
  endif()
  file(TO_CMAKE_PATH "${dir}" dir)
  get_filename_component(dir "${dir}" ABSOLUTE)
  set(HERMETIC_LLVM_CACHE_DIR "${dir}" PARENT_SCOPE)
endfunction()

# Reads a JSON file into ${OUT_VAR}, failing with a useful message.
function(hermetic_llvm_read_json PATH OUT_VAR)
  if(NOT EXISTS "${PATH}")
    hermetic_llvm_fatal("JSON file not found: ${PATH}")
  endif()
  file(READ "${PATH}" content)
  string(JSON _type ERROR_VARIABLE err TYPE "${content}")
  if(err)
    hermetic_llvm_fatal("Failed to parse ${PATH}: ${err}")
  endif()
  set(${OUT_VAR} "${content}" PARENT_SCOPE)
endfunction()

# Downloads (unless present in <cache>/downloads) and extracts an archive into
# <cache>/<KIND>/<NAME>, verifying its SHA-256. The extraction is atomic and
# guarded by a lock so concurrent configures (or try_compile runs) share one
# copy. Re-runs are a stamp-file check.
#
#   hermetic_llvm_fetch_archive(
#     NAME <dir name>  KIND <llvm|sysroot|...>  SHA256 <hex>
#     URLS <url>...  [STRIP_COMPONENTS <n>]  [PATTERNS <glob>...]
#     OUT_DIR <var>)
function(hermetic_llvm_fetch_archive)
  cmake_parse_arguments(A "" "NAME;KIND;SHA256;STRIP_COMPONENTS;OUT_DIR" "URLS;PATTERNS" ${ARGN})
  foreach(required NAME KIND SHA256 URLS OUT_DIR)
    if(NOT A_${required})
      hermetic_llvm_fatal("hermetic_llvm_fetch_archive: missing ${required}")
    endif()
  endforeach()
  if(NOT DEFINED A_STRIP_COMPONENTS)
    set(A_STRIP_COMPONENTS 0)
  endif()
  string(TOLOWER "${A_SHA256}" A_SHA256)

  set(dest "${HERMETIC_LLVM_CACHE_DIR}/${A_KIND}/${A_NAME}")
  set(stamp "${dest}/.hermetic-llvm.stamp")
  if(EXISTS "${stamp}")
    file(READ "${stamp}" existing)
    string(STRIP "${existing}" existing)
    if(existing STREQUAL A_SHA256)
      set(${A_OUT_DIR} "${dest}" PARENT_SCOPE)
      return()
    endif()
  endif()

  file(MAKE_DIRECTORY "${HERMETIC_LLVM_CACHE_DIR}/locks" "${HERMETIC_LLVM_CACHE_DIR}/downloads" "${HERMETIC_LLVM_CACHE_DIR}/${A_KIND}")
  string(REPLACE "/" "-" lock_name "${A_KIND}-${A_NAME}")
  set(lock "${HERMETIC_LLVM_CACHE_DIR}/locks/${lock_name}.lock")
  file(LOCK "${lock}" GUARD FUNCTION TIMEOUT 7200 RESULT_VARIABLE lock_result)
  if(NOT lock_result EQUAL 0)
    hermetic_llvm_fatal("Could not acquire ${lock}: ${lock_result}")
  endif()
  # Another process may have completed the work while we waited.
  if(EXISTS "${stamp}")
    file(READ "${stamp}" existing)
    string(STRIP "${existing}" existing)
    if(existing STREQUAL A_SHA256)
      set(${A_OUT_DIR} "${dest}" PARENT_SCOPE)
      return()
    endif()
  endif()

  list(GET A_URLS 0 first_url)
  string(REGEX REPLACE "[?#].*$" "" basename "${first_url}")
  get_filename_component(basename "${basename}" NAME)
  if(NOT basename MATCHES "\\.(tar\\.(xz|gz|zst|bz2)|tgz|zip)$")
    # URLs without a recognisable archive name (e.g. Chromium's sysroots are
    # addressed by hash); fall back to the target name.
    set(basename "${A_NAME}.tar.xz")
  endif()
  set(archive "${HERMETIC_LLVM_CACHE_DIR}/downloads/${basename}")

  if(EXISTS "${archive}")
    file(SHA256 "${archive}" actual)
    if(NOT actual STREQUAL A_SHA256)
      hermetic_llvm_log("Discarding ${archive}: checksum mismatch")
      file(REMOVE "${archive}")
    else()
      hermetic_llvm_log("Using cached archive ${archive}")
    endif()
  endif()

  if(NOT EXISTS "${archive}")
    set(downloaded FALSE)
    foreach(url IN LISTS A_URLS)
      hermetic_llvm_log("Downloading ${url}")
      set(progress "")
      if(HERMETIC_LLVM_SHOW_PROGRESS)
        set(progress SHOW_PROGRESS)
      endif()
      file(DOWNLOAD "${url}" "${archive}.part"
        EXPECTED_HASH "SHA256=${A_SHA256}"
        STATUS status
        TLS_VERIFY ON
        ${progress}
        ${HERMETIC_LLVM_DOWNLOAD_ARGS})
      list(GET status 0 code)
      list(GET status 1 text)
      if(code EQUAL 0)
        file(RENAME "${archive}.part" "${archive}")
        set(downloaded TRUE)
        break()
      endif()
      file(REMOVE "${archive}.part")
      message(WARNING "[hermetic-llvm] Download of ${url} failed: ${text}")
    endforeach()
    if(NOT downloaded)
      hermetic_llvm_fatal("Could not download ${A_NAME} from any of: ${A_URLS}")
    endif()
  endif()

  hermetic_llvm_log("Extracting ${basename} into ${dest}")
  set(tmp "${dest}.tmp")
  file(REMOVE_RECURSE "${tmp}" "${dest}")
  set(patterns "")
  if(A_PATTERNS)
    set(patterns PATTERNS ${A_PATTERNS})
  endif()
  file(ARCHIVE_EXTRACT INPUT "${archive}" DESTINATION "${tmp}" ${patterns})

  set(current "${tmp}")
  set(remaining "${A_STRIP_COMPONENTS}")
  while(remaining GREATER 0)
    file(GLOB entries LIST_DIRECTORIES true "${current}/*" "${current}/.*")
    list(FILTER entries EXCLUDE REGEX "/\\.\\.?$")
    list(LENGTH entries count)
    if(NOT count EQUAL 1)
      hermetic_llvm_fatal("Cannot strip ${A_STRIP_COMPONENTS} leading path component(s) from ${basename}: ${current} has ${count} entries (${entries})")
    endif()
    list(GET entries 0 current)
    if(NOT IS_DIRECTORY "${current}")
      hermetic_llvm_fatal("Cannot strip path components from ${basename}: ${current} is not a directory")
    endif()
    math(EXPR remaining "${remaining} - 1")
  endwhile()
  file(RENAME "${current}" "${dest}")
  file(REMOVE_RECURSE "${tmp}")
  file(WRITE "${stamp}" "${A_SHA256}\n")
  if(NOT HERMETIC_LLVM_KEEP_ARCHIVES)
    file(REMOVE "${archive}")
  endif()
  set(${A_OUT_DIR} "${dest}" PARENT_SCOPE)
endfunction()

# Appends every FLAG to the string variable VAR (space separated).
macro(hermetic_llvm_append_flags VAR)
  foreach(_flag ${ARGN})
    if("${${VAR}}" STREQUAL "")
      set(${VAR} "${_flag}")
    else()
      set(${VAR} "${${VAR}} ${_flag}")
    endif()
  endforeach()
endmacro()
